#!/usr/bin/env python3
"""Append new pattern entries to past_defi_patterns.csv"""
import csv
from pathlib import Path

CSV_PATH = Path(__file__).resolve().parent.parent / "csv" / "past_defi_patterns.csv"

NEW_ROWS = [
    ["sherlock", "Blueberry (2023-02)", "High", "ChainlinkAdapterOracle will return the wrong price for asset if underlying aggregator hits minAnswer", "Chainlink aggregators have a built in circuit breaker if the price of an asset goes outside of a predetermined price band. If an asset experiences a huge drop in value the oracle will continue to return the minPrice instead of the actual price.", "minAnswer/maxAnswer"],
    ["code4rena", "Moonwell (2023-07)", "High", "No minAnswer/maxAnswer Circuit Breaker Checks while Querying Prices in getChainlinkPrice", "The getChainlinkPrice function retrieves the latest round data from Chainlink. In the event that an asset market price falls below minAnswer or rises above maxAnswer the returned price would still be the boundary value instead of the actual market price.", "minAnswer/maxAnswer"],
    ["sherlock", "USSD (2023-05)", "High", "Risk of Incorrect Asset Pricing by StableOracle in Case of Underlying Aggregator Reaching minAnswer", "If the price of a collateral asset crashes dramatically the Chainlink aggregator will return minAnswer rather than the actual collapsed price. The StableOracle contracts do not validate that the returned price is not at the min/max boundary.", "minAnswer/maxAnswer"],
    ["sherlock", "Sentiment (2023-01)", "Medium", "No check if Arbitrum L2 sequencer is down in Chainlink feeds", "Using Chainlink in L2 chains such as Arbitrum requires checking if the sequencer is down to avoid prices from looking like they are fresh although they are not.", "L2_sequencer"],
    ["sherlock", "Perennial V2 (2023-05)", "Medium", "Missing Sequencer Uptime Feed check can cause unfair liquidations on Arbitrum", "The ChainlinkOracle does not make use of the sequencer uptime feed to check the status of the sequencer.", "L2_sequencer"],
    ["sherlock", "Flat Money (2023-12)", "Medium", "No check if Base L2 sequencer is down in Chainlink feeds", "The _getOnchainPrice() function does not check the Sequencer Uptime Feed to confirm the sequencer status before consuming Chainlink price data.", "L2_sequencer"],
    ["sherlock", "USSD (2023-05)", "High", "The price from StableOracleDAI is returned with the incorrect number of decimals", "The price returned from getPriceUSD is scaled up by 1e10 resulting in 28 decimals instead of 18. The Chainlink DAI/ETH price feed returns 18 decimals but code treats it as 8.", "oracle_decimals"],
    ["sherlock", "Debita Finance (2024-10)", "High", "Chainlink oracle does not account for aggregator decimals making it unusable", "The Debita Chainlink oracle returns the exact price without accounting for the fact that Chainlink does not always return prices in the same decimals.", "oracle_decimals"],
    ["sherlock", "Knox Finance (2022-09)", "Medium", "Chainlink latestRoundData might return stale or incorrect results", "The function uses Chainlink latestRoundData() with no validation that answeredInRound >= roundId that updatedAt > 0 or that price > 0.", "roundId_validation"],
    ["sherlock", "Blueberry (2023-02)", "High", "Chainlink reported answer can be carried over and stale", "The getPrice function does not check answeredInRound against the current roundId. If answeredInRound is less than roundId the answer is stale.", "roundId_validation"],
    ["sherlock", "Blueberry Update", "High", "Potential flash loan attack vulnerability in getPrice function of CurveOracle", "The getPrice function retrieves spot price of each token in a Curve LP pool and multiplies by virtual price. Flash loans can manipulate these values.", "flash_loan_oracle"],
    ["sherlock", "USSD (2023-05)", "High", "Price calculation susceptible to flashloan exploits", "Contract uses uniswap slot0 price instead of TWAP price. slot0 price can be manipulated with flash loans in a single transaction.", "flash_loan_oracle"],
    ["code4rena", "Behodler (2022-01)", "High", "Flash loan price manipulation in purchasePyroFlan()", "An attacker can use a flash loan to push the pool price to exactly the acceptable threshold forcing the protocol to accept a manipulated price.", "flash_loan_oracle"],
    ["sherlock", "Astaria", "High", "Epochs can be progressed during ongoing auctions to cause LP fund loss", "The currentEpoch can be progressed while having an ongoing auction which messes up liquidation logic. Uses fixed duration instead of real timestamp.", "timestamp_auction"],
    ["code4rena", "Nouns Builder (2022-09)", "High", "Same block.timestamp has multiple checkpoint state variables allowing vote manipulation", "getPastVotes() uses binary search which returns a result if it encounters the same timestamp. Timestamps are not unique in the checkpoints array.", "timestamp_manipulation"],
    ["sherlock", "GMX", "High", "User-supplied slippage for decrease orders is ignored", "The user-supplied minOutputAmount parameter for controlling slippage is ignored when a user decreases their position. Infinite slippage is allowed.", "sandwich_mev"],
    ["sherlock", "GMX", "High", "No slippage for withdrawal without swapping path", "When user withdraws in cases without a swapping path there is no minOutputAmount enforcement meaning a MEV bot can sandwich the withdrawal.", "sandwich_mev"],
    ["sherlock", "Optimism", "High", "Malicious user can finalize others withdrawal with less than specified gas limit", "Transactions to execute a withdrawal can be sent with 5122 less gas than specified. A malicious user can call finalizeWithdrawalTransaction() causing silent failure.", "gas_griefing"],
    ["sherlock", "Knox Finance", "High", "Unbounded loop in _previewWithdraw and _redeemMax Can Lead To DoS", "Unbounded loops go through all orders in orderbook costing gas and may revert due to exceeding the block gas limit.", "unbounded_loop"],
    ["sherlock", "OpenQ", "High", "Refunds can be bricked by triggering OOG in DepositManager", "The DepositManager runs a for loop over an unbounded array. This array can be made large enough to exceed the block gas limit stopping refunds.", "unbounded_loop"],
    ["sherlock", "Carapace", "High", "Lending pool state transition will be broken when pool is expired in late state", "When a pool expires while in late state the state machine transitions incorrectly permanently locking capital.", "state_transition"],
    ["sherlock", "Carapace", "High", "Protection sellers can bypass withdrawal delay mechanism", "Withdrawal delay mechanism can be bypassed by creating a withdraw request in each cycle allowing front-running of default events.", "state_transition"],
    ["sherlock", "Fair Funding (Alchemix)", "High", "Incorrect shares accounting causes liquidations to fail", "Accounting mismatch when marking claimable yield against vault shares causes failing liquidations. total_shares is not updated.", "token_accounting"],
    ["sherlock", "GMX", "High", "Incorrect parameter ordering in updateTotalBorrowing", "The ordering of parameters in updateTotalBorrowing() is incorrect causing internal accounting to diverge from actual balances.", "token_accounting"],
    ["sherlock", "Astaria", "High", "_deleteLienPosition can be called by anyone", "_deleteLienPosition is a public function without caller check. Anyone can remove any lien from any collateral.", "missing_access_control"],
    ["sherlock", "Notional", "High", "Bought Token Can Be Sent To Attacker Wallet Using 0x Adaptor", "Lack of recipient validation allows purchased tokens to be sent to attacker wallet. settleVaultEmergency is permissionless.", "missing_access_control"],
    ["sherlock", "Midas", "High", "Malicious users can bypass the blacklist via renounceRole", "Users can bypass the blacklist through OpenZeppelin renounceRole function which is unguarded.", "default_admin_role"],
    ["code4rena", "Livepeer (2022-01)", "Medium", "DEFAULT_ADMIN_ROLE can approve arbitrary address to spend from L1Escrow", "L1Escrow approve() allows DEFAULT_ADMIN_ROLE to approve any spender for any value on any token held in escrow.", "default_admin_role"],
    ["sherlock", "Cooler", "High", "Use safeTransfer consistently — return value not checked", "Some tokens do not revert on failure but return false. transfer/transferFrom is used and the return value is not checked.", "erc20_return_value"],
    ["sherlock", "Bond Options", "High", "All funds can be stolen from FixedStrikeOptionTeller using fee-on-transfer token", "The create function records the nominal sent amount rather than the actual received amount allowing exploitation via fee-on-transfer tokens.", "fee_on_transfer"],
    ["sherlock", "Sentiment", "Medium", "Balances of rebasing tokens are not properly tracked", "Rebasing tokens where balanceOf() changes over time are not properly tracked. Internal accounting diverges from actual balances.", "fee_on_transfer"],
    ["code4rena", "Asymmetry (2023-03)", "High", "Front-running Exploit Allows Stakers to Bypass PauseUnstaking Mechanisms", "A staker may bypass pause control by front-running the pause() transaction with a requestUnstake() call.", "pausable_bypass"],
    ["sherlock", "GMX", "Medium", "When underlying collateral tokens are paused orders cannot be canceled", "When underlying collateral tokens are paused orders cannot be canceled and will be executed immediately after unpause.", "pausable_bypass"],
    ["sherlock", "TITLES Protocol", "Medium", "Incompatibility of Upgradeability Pattern in TitlesGraph Contract", "TitlesGraph is designed as UUPSUpgradeable but instantiated via constructor. Implementation is uninitialized and vulnerable to takeover.", "init_frontrun"],
    ["code4rena", "Rigor (2022-08)", "High", "Community escrow allows for signature replay", "checkSignatureValidity() does not utilize nonces and can be tricked by replaying signatures from earlier calls.", "sig_replay"],
    ["sherlock", "Harpie", "Medium", "Cross-chain replay attacks are possible with changeRecipientAddress()", "There is no chainId in the signed data for changeRecipientAddress(). An attacker can replay the action on the correct chain.", "sig_replay"],
]

with open(CSV_PATH, "a", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    for row in NEW_ROWS:
        writer.writerow(row)

print(f"Added {len(NEW_ROWS)} rows to CSV")
